title: "Friends of St Michaels Uganda"
extitle: "Friends of St. Michael’s Girls Primary School Busembatia Uganda"
timezone: BST
url: http://beta.fsmu.co.uk
tracking_code: 
color:
  primary: "#dd9933"
  secondary: "#836953"
logo: 
permalink: "/blog/:year/:title/"
section: Blog

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  - name: Facebook
    icon: facebook-f
    site: 'https://www.facebook.com/fsmuganda'
    
  - name: Twitter
    icon: twitter
    site: 'https://twitter.com/fsmuganda'
    
  - name: Google Plus
    icon: google-plus
    site: 'https://plus.google.com/+FSMUcoukUganda/about'
    
  - name: Youtube
    icon: youtube
    site: 'https://www.youtube.com/channel/UCkbB9Bum0NuqVY5dBH1wEkw'
    
menu:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Projects
    link: /projects
  - name: News
    link: /news
  - name: Gallery
    link: /gallery
  - name: Contact
    link: contact

sass:
  sass_dir: assets/styles
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs:
    - development
    
collections:
  partners:
