title: "Friends of St Michaels Uganda"
extitle: "Friends of St. Michael’s Girls Primary School Busembatia Uganda"
timezone: BST
url: https://fsmu.co.uk
tracking_code: 
color:
  primary: "#dd9933"
  secondary: "#836953"
logo: 
permalink: "/blog/:year/:title/"
section: Blog

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

social:
  - name: Facebook
    icon: facebook-f
    site: 'https://www.facebook.com/fsmuganda'
    
  - name: Twitter
    icon: twitter
    site: 'https://twitter.com/fsmuganda'
    
  - name: Google Plus
    icon: google-plus
    site: 'https://plus.google.com/+FSMUcoukUganda/about'
    
  - name: Instagram
    icon: instagram
    site: 'https://www.instagram.com/fsmuganda/'
    
menu:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Projects
    link: /projects
  - name: News
    link: /news
  - name: Volunteers
    link: /volunteers
  - name: Gallery
    link: /gallery
  - name: Contact
    link: /contact

sass:
  sass_dir: assets/styles
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs:
    - development
    
collections:
  projects:
    output: true
    layout: page
    permalink: /:collection/:name/
