title: Friends of St Michaels Uganda
timezone: BST
url: https://fsmu.co.uk
tracking_code: 
color:
  primary: "#dd9933"
  secondary: "#836953"
logo: 
permalink: "/blog/:year/:title/"
section: Blog
sass:
  sass_dir: assets/styles
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs:
    - development
