---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
upload_dir: assets/images
public_path: "{{ site.baseurl }}/assets/images"
front_matter_path: "/assets/images"
use_front_matter_path: true
file_template: ":filename:"
